put selenium at end and update code

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -7,16 +7,16 @@ pool: myPool
 
 variables:
   python.version: '3.7.6'
-  azureServiceConnectionId: 'ab43008d-e2a5-42e0-a87d-5fdbd6912c81'
+  azureServiceConnectionId: '1f3adfd5-a51a-40ec-899e-7a9a05837992'
   projectRoot: $(System.DefaultWorkingDirectory)
-  subscriptionId: 'a785336a-35d8-4efd-80be-93d34a9e4b66'
+  subscriptionId: '0fadec41-9b39-430f-aa5d-ce7b49f9346c'
   resourceGroupName: 'Azuredevops'
-  armBackendStorageAccountName: 'tfstate91224001'
+  armBackendStorageAccountName: 'tfstate207391737'
   armBackendContainerName: 'tfstate'
   packerImageName: 'myPackerImage'
   environmentName: 'myEnvironment'
-  azureWebAppName: 'webapp-0254563186'
-  webAppUrl: 'https://webapp-0254563186.azurewebsites.net'
+  azureWebAppName: 'webapp-odluser284939'
+  webAppUrl: 'https://webapp-odluser284939.azurewebsites.net'
 
 stages:
 #--------------------------------------------#  
@@ -191,68 +191,6 @@ stages:
           #     echo "Health check"
           #     curl -s -o /dev/null -w "%{http_code}" $(webAppUrl)/api/v1/Activities
 
-#--------------------------------------------#  
-# SELENIUM TESTS STAGE
-#--------------------------------------------#    
-- stage: SeleniumTests
-  jobs:
-  - deployment: SeleniumDeploy
-    pool:
-      name: 'myPool'
-    displayName: Selenium Tests
-    environment: 'myEnvironment'
-    strategy:
-      runOnce:
-        deploy:
-          steps:
-          - task: DownloadPipelineArtifact@2
-            inputs:
-              artifact: drop-ui-tests
-              path: $(Pipeline.Workspace)/drop-ui-tests
-          - script: |
-              unzip -o $(Pipeline.Workspace)/drop-ui-tests/$(Build.BuildId)-ui-tests.zip -d $(Pipeline.Workspace)/drop-ui-tests/ui-tests
-            displayName: 'Unzip Selenium Tests'
-          - task: Bash@3
-            inputs:
-              targetType: 'inline'
-              script: |
-                set -e
-                sudo apt-get update
-
-                set +e
-                sudo apt-get upgrade -y
-                UPGRADE_CODE=$?
-                set -e
-
-                if [ "$UPGRADE_CODE" -ne 0 ] && [ "$UPGRADE_CODE" -ne 8 ]; then
-                  echo "apt-get upgrade failed $UPGRADE_CODE"
-                  exit $UPGRADE_CODE
-                fi
-                sudo apt-get install -y wget unzip python3-pip
-                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-                sudo apt-get install -y ./google-chrome-stable_current_amd64.deb || true
-                CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -n1)
-                CHROMEDRIVER_VERSION=$(wget -q -O - "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
-                wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
-                unzip -o chromedriver_linux64.zip
-                sudo mv chromedriver /usr/local/bin/chromedriver
-                chmod +x /usr/local/bin/chromedriver
-
-                pip3 install selenium
-
-                cd $(Pipeline.Workspace)/drop-ui-tests/ui-tests
-                python3 main.py --headless || exit 1
-
-                pip3 install selenium
-
-                cd $(Pipeline.Workspace)/drop-ui-tests/ui-tests
-                python3 main.py --headless || exit 1
-          - publish: $(Pipeline.Workspace)/drop-ui-tests/ui-tests/selenium.log
-            artifact: selenium-report
-            displayName: 'Publish Selenium Reports'
-          
-
-
 
 #--------------------------------------------#  
 # JMETER TESTS STAGE
@@ -336,3 +274,65 @@ stages:
           - publish: postman-tests/postman.xml
             artifact: postman-report
             displayName: 'Publish Postman Report'
+
+
+
+#--------------------------------------------#  
+# SELENIUM TESTS STAGE
+#--------------------------------------------#    
+- stage: SeleniumTests
+  jobs:
+  - deployment: SeleniumDeploy
+    pool:
+      name: 'myPool'
+    displayName: Selenium Tests
+    environment: 'myEnvironment'
+    strategy:
+      runOnce:
+        deploy:
+          steps:
+          - task: DownloadPipelineArtifact@2
+            inputs:
+              artifact: drop-ui-tests
+              path: $(Pipeline.Workspace)/drop-ui-tests
+          - script: |
+              unzip -o $(Pipeline.Workspace)/drop-ui-tests/$(Build.BuildId)-ui-tests.zip -d $(Pipeline.Workspace)/drop-ui-tests/ui-tests
+            displayName: 'Unzip Selenium Tests'
+          - task: Bash@3
+            inputs:
+              targetType: 'inline'
+              script: |
+                set -e
+                sudo apt-get update
+
+                set +e
+                sudo apt-get upgrade -y
+                UPGRADE_CODE=$?
+                set -e
+
+                if [ "$UPGRADE_CODE" -ne 0 ] && [ "$UPGRADE_CODE" -ne 8 ]; then
+                  echo "apt-get upgrade failed $UPGRADE_CODE"
+                  exit $UPGRADE_CODE
+                fi
+                sudo apt-get install -y wget unzip python3-pip
+                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+                sudo apt-get install -y ./google-chrome-stable_current_amd64.deb || true
+                CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -n1)
+                CHROMEDRIVER_VERSION=$(wget -q -O - "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
+                wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
+                unzip -o chromedriver_linux64.zip
+                sudo mv chromedriver /usr/local/bin/chromedriver
+                chmod +x /usr/local/bin/chromedriver
+
+                pip3 install selenium
+
+                cd $(Pipeline.Workspace)/drop-ui-tests/ui-tests
+                python3 main.py --headless || exit 1
+
+                pip3 install selenium
+
+                cd $(Pipeline.Workspace)/drop-ui-tests/ui-tests
+                python3 main.py --headless || exit 1
+          - publish: $(Pipeline.Workspace)/drop-ui-tests/ui-tests/selenium.log
+            artifact: selenium-report
+            displayName: 'Publish Selenium Reports'
